// AUTO-GENERATED by scripts/fetch-os-contributions.mjs
// Last updated: 2026-03-01T16:08:43.922Z
// Do not edit manually — run: npm run fetch:os

export interface OSContribution {
    repo:      string;
    title:     string;
    url:       string;
    state:     "open" | "closed" | "merged";
    createdAt: string;
}

export const openSourceContributions: OSContribution[] = [
    { repo: "facebook/pyrefly", title: "Splitting unknown-name error code", url: "https://github.com/facebook/pyrefly/pull/2584", state: "open", createdAt: "2026-02-27" },
    { repo: "facebook/pyrefly", title: "fix: 'Go to symbol' now includes methods inside a class", url: "https://github.com/facebook/pyrefly/pull/2109", state: "closed", createdAt: "2026-01-14" },
    { repo: "facebook/pyrefly", title: "fix: resolved generic resolution when parameterised ", url: "https://github.com/facebook/pyrefly/pull/1915", state: "closed", createdAt: "2025-12-22" },
    { repo: "facebook/pyrefly", title: "fix: quote marks during autocomplete now take care of the existing quotes ", url: "https://github.com/facebook/pyrefly/pull/1666", state: "closed", createdAt: "2025-11-22" },
    { repo: "Nexus-VITC/Club-Website", title: "Made Website Responsive", url: "https://github.com/Nexus-VITC/Club-Website/pull/4", state: "open", createdAt: "2025-07-15" },
];
